### ISSUE TITLE
missing image files for documentation

### ISSUE THREAD

**Issue by dsclassen** [bl831/bin_stuff#4]
The following image files are referenced in noisily.md, but are missing:

```
nanoBragg_tmb.jpg
nanoBragg_zoom_tmb.jpg
upscaled_tmb.jpg
upscaled_zoom_tmb.jpg
psfed_tmb.jpg
psfed_zoom_tmb.jpg
```

**Comment by jmholton** [comment]
pushed. But FYI, any and all missing things can be found in the original html documentation under ~jamesh/html/bin_stuff/

**Comment by dsclassen** [comment]
Sure... I could just fix this for you, but I think it is a useful exercise for the both of us to use the `git` tools to create issues and then resolve them.
